In [1]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits

digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [3]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

C:\Users\ACER\.conda\envs\condaenv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9481481481481482

In [4]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9777777777777777

The issue: If I run the second cell (train_test_split) again, the results of the preceeding models will change each time.
Not a good way to measure which model is the best for a use case.

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3) # stating how many folds I want to be created.Here,3.Conventionally,10.
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [11]:
# kf.split will return an iterator, the iterator will return train_index and test_index for each of the iterations
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)
#Explanation for output below:
# First fold, [0,1,2] are the tests. Next fold, [3,4,5] are the tests.

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [16]:
# just an example of modularization of the above cells 3 to 5
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9851851851851852

In [17]:
# StratifiedKFold is better than KFold because it uniformizes each fold group
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [38]:
scores_le = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    scores_le.append(get_score(LogisticRegression(max_iter=10000),X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(),X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train, X_test, y_train, y_test))

print(train_index)
print(test_index)
    
print(scores_le)
print(scores_svm)
print(scores_rf)

[   0    1    2 ... 1207 1215 1221]
[1185 1190 1192 1194 1195 1196 1197 1201 1203 1204 1205 1206 1208 1209
 1210 1211 1212 1213 1214 1216 1217 1218 1219 1220 1222 1223 1224 1225
 1226 1227 1228 1229 1230 1231 1232 1233 1234 1235 1236 1237 1238 1239
 1240 1241 1242 1243 1244 1245 1246 1247 1248 1249 1250 1251 1252 1253
 1254 1255 1256 1257 1258 1259 1260 1261 1262 1263 1264 1265 1266 1267
 1268 1269 1270 1271 1272 1273 1274 1275 1276 1277 1278 1279 1280 1281
 1282 1283 1284 1285 1286 1287 1288 1289 1290 1291 1292 1293 1294 1295
 1296 1297 1298 1299 1300 1301 1302 1303 1304 1305 1306 1307 1308 1309
 1310 1311 1312 1313 1314 1315 1316 1317 1318 1319 1320 1321 1322 1323
 1324 1325 1326 1327 1328 1329 1330 1331 1332 1333 1334 1335 1336 1337
 1338 1339 1340 1341 1342 1343 1344 1345 1346 1347 1348 1349 1350 1351
 1352 1353 1354 1355 1356 1357 1358 1359 1360 1361 1362 1363 1364 1365
 1366 1367 1368 1369 1370 1371 1372 1373 1374 1375 1376 1377 1378 1379
 1380 1381 1382 1383 1384 1385 1386 1387 

In [34]:
len(digits.data)

1797

In [35]:
len(digits.target)

1797

In [42]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(), digits.data, digits.target, cv=3)

C:\Users\ACER\.conda\envs\condaenv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\ACER\.conda\envs\condaenv\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-

array([0.92153589, 0.94156928, 0.91652755])

In [44]:
cross_val_score(SVC(), digits.data, digits.target, cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [47]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93322204, 0.94824708, 0.91318865])

In [49]:
# cross validation technique used to not just compare different models performance,but hyperparameter tuning as seen here, changing number of trees
cross_val_score(RandomForestClassifier(n_estimators=15), digits.data, digits.target, cv=3)

array([0.90984975, 0.93489149, 0.90317195])

In [50]:
# cross validation technique used to not just compare different models performance,but hyperparameter tuning as seen here
cross_val_score(RandomForestClassifier(n_estimators=60), digits.data, digits.target, cv=3)

array([0.94323873, 0.94657763, 0.92153589])